### ISSUE TITLE
Conda Virtual environment name not visible

### ISSUE THREAD

**Issue by ParthBibekar** [andresgongora/synth-shell-prompt#16] opened 2021-06-04 15:15 UTC
Hi,
Whenever I activate a virtual environment, it doesn't show that the environment has been activated. 
Usually a terminal shows this   `(environment-name) user@ubuntu-budgie:$  `
It would be nice to have something like this in synth-shell as well.

**Comment by andresgongora** [comment] 2021-06-04 17:06
I guess conda is gaining lots of track - same request as in #15

**Comment by andresgongora** [comment] 2021-08-11 10:47
Can you guys test whether 937991e works as intended? It should first check for conda environments, then for python environments, and if none, do nothing :)

**Comment by ParthBibekar** [comment] 2021-08-11 12:08
Yes it works completely fine for me. Thanks a lot!

**Comment by andresgongora** [comment] 2021-10-07 04:45
@ParthBibekar Ok! I'll close this issue then for now. If any issue comes up, feel free to reopen it ;)

**Closed by andresgongora** 2021-10-07 04:45 UTC
